### ISSUE TITLE
Parentheses

### ISSUE THREAD

**Issue by ghost** [interactivefics/interactive-fics#1]
I find that when I am using the tool, parens always appear around my name, because authors seem to use (Y/N) instead of Y/N.
Could we fix this so it gets rid of parens?

**Comment by ghost** [comment]
Oddly enough, your JS code looks like it should fix this.

**Comment by mariamrf** [comment]
It's true that the previous version supported this, but not anymore; I reverted back to using regex to find the Y/N value to fix another bug. It's finally my weekend so hopefully I'll fix that + the issue with the "infinite scroll" thing.

**Comment by ghost** [comment]
Alright, thank you!
