### ISSUE TITLE
Underscores instead of Y/N

### ISSUE THREAD

**Issue by ghost** [interactivefics/interactive-fics#2]
So I had an idea: since a lot of fic also uses ____ to denote Y/N, could we implement this as well as Y/N y/n Y/n y/N etc?

**Comment by mariamrf** [comment]
I thought about that. But there are some obstacles:

<ol><li>Everyone uses a different number of underscores.</li>
<li>Even if we set it to, like, three, or any repeated occurrence of underscores there's no guarantee the user won't encounter a similar set somewhere else where it <i>isn't</i> a story which would make the extension very annoying.</li></ol>

So the answer is: we <b>can</b> but we definitely <b>shouldn't</b>.

**Comment by ghost** [comment]
Okay
