### ISSUE TITLE
Have to re-input name every page

### ISSUE THREAD

**Issue by ghost** [interactivefics/interactive-fics#3]
Whenever I'm on DeviantArt it never saves (i guess) and so I have to put in my name every time the next part loads.

**Comment by mariamrf** [comment]
Could you provide me with a link or a screenshot?
Were you using the extension while incognito?

**Comment by ghost** [comment]
I was not in Incognito, and I just clicked the next part or a new fic on the side, and it resets to Y/N so I have to put it in every part
Screenshots:
![11thdoctorxreader- cool and hot by exuberantstarchild on deviantart 1](https://cloud.githubusercontent.com/assets/10751894/6658261/a879b560-cb20-11e4-87bd-08288b65941f.png)
![11thdoctorxreader- when we re old by exuberantstarchild on deviantart](https://cloud.githubusercontent.com/assets/10751894/6658262/a9908258-cb20-11e4-8024-8b41e39eb1d7.png)

**Comment by mariamrf** [comment]
Hi! Sorry this is a late reply, but this issue has been solved with the latest update. If you are still experiencing problems, please let me know.
